version: '3.9'
services:
  db:
    image: mysql:8.0.29
    #command: - mysqld --default-authentication-plugin=mysql_native_password
    restart:
      always
    environment:
      TZ: America/Sao_paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: dbaplicacaobackend
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - aplicacaobackend-network
    volumes:
      - mysql_data:/var/lib/mysql

  aplicacaobackend:
    image: gmpatrick/aplicacaobackend
    restart:
      always
    build:
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_paulo
      spring.datasource.url: jdbc:mysql://db:3308/dbaplicacaobackend
      spring.datasource.username: root
      spring.datasource.password: admin123
    ports:
      - 8080:8080
    command:
      - mvn spring-boot:run
    depends_on:
      - db
    networks:
      - aplicacaobackend-network

networks:
  aplicacaobackend-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local