server:
  port: 8080

spring:
  application:
    name: aplicacao-back-end

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/dbaplicacaobackend?useTimezone=true&serverTimeZone=UTC
    username: docker
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
    open-in-view: false